const vietnamAbc = {
  "Hồ Chí Minh": [
    "Quận 1",
    "Quận 2",
    "Quận 3",
    "Quận 4",
    "Quận 5",
    "Quận 6",
    "Quận 7",
    "Quận 8",
    "Quận 9",
    "Quận 10",
    "Quận 11",
    "Quận 12",
    "Bình Tân",
    "Bình Thạnh",
    "Gò Vấp",
    "Phú Nhuận",
    "Tân Bình",
    "Tân Phú",
    "Thủ Đức",
  ],
  "Hà Nội": [
    "Ba Đình",
    "Ứng Hòa",
    "Hoàn Kiếm",
    "Hai Bà Trưng",
    "Đống Đa",
    "Cầu Giấy",
    "Thanh Xuân",
    "Hoàng Mai",
    "Long Biên",
    "Bắc Từ Liêm",
    "Nam Từ Liêm",
    "Hà Đông",
    "Sơn Tây",
    "Ba Vì",
    "Phúc Thọ",
    "Thạch Thất",
    "Quốc Oai",
    "Chương Mỹ",
    "Thanh Oai",
    "Thanh Trì",
    "Mê Linh",
    "Đan Phượng",
    "Hoài Đức",
    "Thanh Xuân",
    "Gia Lâm",
    "Đông Anh",
    "Sóc Sơn",
    "Mỹ Đức",
  ],
  "Đà Nẵng": [
    "Hải Châu",
    "Thanh Khê",
    "Sơn Trà",
    "Ngũ Hành Sơn",
    "Liên Chiểu",
    "Hòa Vang",
    "Cẩm Lệ",
  ],
  "Cần Thơ": ["Ninh Kiều", "Bình Thủy", "Cái Răng", "Ô Môn", "Thốt Nốt"],
  "Hải Phòng": [
    "Hồng Bàng",
    "Ngô Quyền",
    "Lê Chân",
    "Hải An",
    "Kiến An",
    "Đồ Sơn",
    "An Dương",
    "An Lão",
    "Kiến Thuỵ",
    "Tiên Lãng",
    "Vĩnh Bảo",
    "Cát Hải",
    "Bạch Long Vĩ",
  ],
  "Đồng Nai": [
    "Biên Hòa",
    "Long Khánh",
    "Nhơn Trạch",
    "Cẩm Mỹ",
    "Vĩnh Cửu",
    "Tân Phú",
    "Xuân Lộc",
  ],
  "Bình Dương": [
    "Thủ Dầu Một",
    "Bến Cát",
    "Dĩ An",
    "Phú Giáo",
    "Tân Uyên",
    "Thuận An",
    "Dầu Tiếng",
  ],
  "Hưng Yên": [
    "Hưng Yên",
    "Văn Lâm",
    "Văn Giang",
    "Yên Mỹ",
    "Mỹ Hào",
    "Ân Thi",
    "Khoái Châu",
    "Kim Động",
    "Tiên Lữ",
  ],
  "Long An": [
    "Tân An",
    "Kiến Tường",
    "Tân Hưng",
    "Vĩnh Hưng",
    "Mộc Hóa",
    "Tân Thạnh",
    "Thạnh Hóa",
    "Đức Hòa",
    "Đức Huệ",
    "Bến Lức",
    "Thủ Thừa",
    "Châu Thành",
    "Tân Trụ",
    "Cần Đước",
    "Cần Giuộc",
  ],
  "Bình Thuận": ["Phan Thiết", "La Gi"],
  "Bình Định": [
    "Quy Nhơn",
    "An Nhơn",
    "Hoài Nhơn",
    "Tây Sơn",
    "Phù Cát",
    "Vân Canh",
    "Tuy Phước",
    "An Lão",
    "Hoài Ân",
  ],
  "Gia Lai": [
    "Pleiku",
    "An Khê",
    "Ayun Pa",
    "Chư Păh",
    "Chư Prông",
    "Chư Sê",
    "Đăk Đoa",
    "Đăk Pơ",
    "Đức Cơ",
    "Ia Grai",
    "Ia Pa",
    "Kbang",
    "Kông Chro",
    "Krông Pa",
    "Mang Yang",
  ],
  "Bạc Liêu": [
    "Bạc Liêu",
    "Hòa Bình",
    "Đông Hải",
    "Giá Rai",
    "Hòn Đất",
    "Phước Long",
    "Vĩnh Lợi",
  ],
  "Cà Mau": [
    "Cà Mau",
    "U Minh",
    "Thới Bình",
    "Trần Văn Thời",
    "Cái Nước",
    "Đầm Dơi",
    "Năm Căn",
    "Phú Tân",
  ],
  "Cao Bằng": [
    "Cao Bằng",
    "Bảo Lâm",
    "Bảo Lạc",
    "Hà Quảng",
    "Hòa An",
    "Nguyên Bình",
    "Quảng Uyên",
    "Thạch An",
    "Trùng Khánh",
  ],
  "Bắc Giang": [
    "Bắc Giang",
    "Hiệp Hòa",
    "Lạng Giang",
    "Lục Nam",
    "Lục Ngạn",
    "Sơn Động",
    "Tân Yên",
    "Việt Yên",
    "Yên Dũng",
    "Yên Thế",
  ],
  "Bắc Kạn": [
    "Bắc Kạn",
    "Bạch Thông",
    "Chợ Đồn",
    "Na Rì",
    "Ngân Sơn",
    "Ba Bể",
    "Pác Nặm",
  ],
  "Bắc Ninh": [
    "Bắc Ninh",
    "Gia Bình",
    "Lương Tài",
    "Quế Võ",
    "Thuận Thành",
    "Tiên Du",
    "Từ Sơn",
    "Yên Phong",
  ],
  "Bến Tre": [
    "Bến Tre",
    "Ba Tri",
    "Bình Đại",
    "Châu Thành",
    "Chợ Lách",
    "Giồng Trôm",
    "Mỏ Cày",
    "Thạnh Phú",
  ],
  "Bà Rịa - Vũng Tàu": [
    "Vũng Tàu",
    "Bà Rịa",
    "Châu Đức",
    "Côn Đảo",
    "Đất Đỏ",
    "Long Điền",
    "Tân Thành",
    "Xuyên Mộc",
  ],
  "An Giang": [
    "Long Xuyên",
    "Châu Đốc",
    "An Phú",
    "Châu Phú",
    "Châu Thành",
    "Chợ Mới",
    "Phú Tân",
    "Tân Châu",
    "Thới Lai",
  ],
  "Bắc Ninh": [
    "Bắc Ninh",
    "Gia Bình",
    "Lương Tài",
    "Quế Võ",
    "Thuận Thành",
    "Tiên Du",
    "Từ Sơn",
    "Yên Phong",
  ],
  "Bình Dương": [
    "Thủ Dầu Một",
    "Bến Cát",
    "Dĩ An",
    "Phú Giáo",
    "Tân Uyên",
    "Thuận An",
    "Dầu Tiếng",
  ],
  "Bình Phước": [
    "Đồng Xoài",
    "Bình Long",
    "Bù Đăng",
    "Bù Đốp",
    "Bù Gia Mập",
    "Chơn Thành",
    "Đồng Phú",
    "Hớn Quản",
    "Lộc Ninh",
    "Phú Riềng",
  ],
  "Bình Thuận": [
    "Phan Thiết",
    "La Gi",
    "Bắc Bình",
    "Đức Linh",
    "Hàm Thuận Bắc",
    "Hàm Thuận Nam",
    "Hòa Bình",
    "Phú Quý",
    "Tánh Linh",
    "Tuy Phong",
  ],
  "Cà Mau": [
    "Cà Mau",
    "U Minh",
    "Thới Bình",
    "Trần Văn Thời",
    "Cái Nước",
    "Đầm Dơi",
    "Năm Căn",
    "Phú Tân",
  ],
  "Cần Thơ": ["Ninh Kiều", "Bình Thủy", "Cái Răng", "Ô Môn", "Thốt Nốt"],
  "Đắk Lắk": [
    "Buôn Ma Thuột",
    "Buôn Hồ",
    "Buôn Đôn",
    "Buôn Đức",
    "Cư Kuin",
    "Cư M'gar",
    "Ea H'leo",
    "Ea Kar",
    "Ea Súp",
    "Krông Ana",
    "Krông Búk",
    "Krông Năng",
    "Krông Pắc",
    "Lắk",
    "M'Đrắk",
  ],
  "Đồng Nai": [
    "Biên Hòa",
    "Long Khánh",
    "Nhơn Trạch",
    "Cẩm Mỹ",
    "Vĩnh Cửu",
    "Tân Phú",
    "Xuân Lộc",
  ],
  "Đồng Tháp": [
    "Cao Lãnh",
    "Hồng Ngự",
    "Lai Vung",
    "Tam Nông",
    "Tân Hồng",
    "Thanh Bình",
    "Tháp Mười",
    "Châu Thành",
    "Hồng Ngự",
    "Lấp Vò",
    "Tân Phú",
    "Thị Xã Hồng Ngự",
  ],
  "Gia Lai": [
    "Pleiku",
    "An Khê",
    "Ayun Pa",
    "Chư Păh",
    "Chư Prông",
    "Chư Sê",
    "Đăk Đoa",
    "Đăk Pơ",
    "Đức Cơ",
    "Ia Grai",
    "Ia Pa",
    "Kbang",
    "Kông Chro",
    "Krông Pa",
    "Mang Yang",
  ],
  "Hà Giang": [
    "Hà Giang",
    "Bắc Mê",
    "Bắc Quang",
    "Đồng Văn",
    "Hoàng Su Phì",
    "Mèo Vạc",
    "Quản Bạ",
    "Quang Bình",
    "Vị Xuyên",
    "Xín Mần",
    "Yên Minh",
  ],
  "Hà Nam": ["Phủ Lý", "Duy Tiên", "Kim Bảng", "Lý Nhân", "Thanh Liêm"],
  "Hà Tĩnh": [
    "Hà Tĩnh",
    "Cẩm Xuyên",
    "Hồng Lĩnh",
    "Hương Khê",
    "Hương Sơn",
    "Kỳ Anh",
    "Lộc Hà",
    "Nghi Xuân",
    "Thạch Hà",
    "Vũ Quang",
  ],
  "Hải Dương": [
    "Hải Dương",
    "Chí Linh",
    "Nam Sách",
    "Kim Thành",
    "Kinh Môn",
    "Thanh Hà",
    "Thanh Miện",
    "Cẩm Giàng",
    "Ninh Giang",
    "Gia Lộc",
    "Tứ Kỳ",
  ],
  "Hậu Giang": [
    "Vị Thanh",
    "Long Mỹ",
    "Ngã Bảy",
    "Châu Thành A",
    "Châu Thành",
    "Phụng Hiệp",
  ],
  "Hòa Bình": [
    "Hòa Bình",
    "Cao Phong",
    "Đà Bắc",
    "Kim Bôi",
    "Kỳ Sơn",
    "Lạc Sơn",
    "Lạc Thủy",
    "Lương Sơn",
    "Mai Châu",
    "Tân Lạc",
    "Yên Thủy",
  ],
  "Hưng Yên": [
    "Hưng Yên",
    "Văn Lâm",
    "Văn Giang",
    "Yên Mỹ",
    "Mỹ Hào",
    "Ân Thi",
    "Khoái Châu",
    "Kim Động",
    "Tiên Lữ",
  ],
  "Khánh Hòa": [
    "Nha Trang",
    "Cam Ranh",
    "Ninh Hòa",
    "Diên Khánh",
    "Vạn Ninh",
    "Khánh Sơn",
    "Trường Sa",
  ],
  "Kiên Giang": [
    "Rạch Giá",
    "Hà Tiên",
    "Kiên Lương",
    "Hòn Đất",
    "Tân Hiệp",
    "Châu Thành",
    "Giồng Riềng",
    "Gò Quao",
    "An Biên",
    "An Minh",
    "Vĩnh Thuận",
    "Phú Quốc",
    "Kiên Hải",
    "U Minh Thượng",
    "Giang Thành",
  ],
  "Kon Tum": [
    "Kon Tum",
    "Đắk Glei",
    "Đắk Hà",
    "Đắk Tô",
    "Ia H'Drai",
    "Kon Plông",
    "Kon Rẫy",
    "Ngọc Hồi",
    "Sa Thầy",
    "Tu Mơ Rông",
  ],
  "Lai Châu": [
    "Lai Châu",
    "Tam Đường",
    "Mường Tè",
    "Phong Thổ",
    "Sìn Hồ",
    "Than Uyên",
    "Tân Uyên",
    "Nậm Nhùn",
  ],
  "Lâm Đồng": [
    "Đà Lạt",
    "Bảo Lộc",
    "Bảo Lâm",
    "Đạ Huoai",
    "Đạ Tẻh",
    "Đam Rông",
    "Di Linh",
    "Đơn Dương",
    "Đức Trọng",
    "Lạc Dương",
  ],
  "Lạng Sơn": [
    "Lạng Sơn",
    "Bắc Sơn",
    "Bình Gia",
    "Cao Lộc",
    "Chi Lăng",
    "Đình Lập",
    "Hữu Lũng",
    "Lộc Bình",
    "Tràng Định",
    "Văn Lãng",
    "Văn Quan",
  ],
  "Lào Cai": [
    "Lào Cai",
    "Bảo Thắng",
    "Bảo Yên",
    "Bát Xát",
    "Bắc Hà",
    "Mường Khương",
    "Sa Pa",
    "Văn Bàn",
  ],
  "Long An": [
    "Tân An",
    "Kiến Tường",
    "Tân Hưng",
    "Vĩnh Hưng",
    "Mộc Hóa",
    "Tân Thạnh",
    "Thạnh Hóa",
    "Đức Hòa",
    "Đức Huệ",
    "Bến Lức",
    "Thủ Thừa",
    "Châu Thành",
    "Tân Trụ",
    "Cần Đước",
    "Cần Giuộc",
  ],
  "Nam Định": [
    "Nam Định",
    "Giao Thủy",
    "Hải Hậu",
    "Mỹ Lộc",
    "Nam Trực",
    "Nghĩa Hưng",
    "Trực Ninh",
    "Vụ Bản",
    "Xuân Trường",
    "Ý Yên",
  ],
  "Nghệ An": [
    "Vinh",
    "Cửa Lò",
    "Thái Hoà",
    "Yên Thành",
    "Quỳ Châu",
    "Quỳ Hợp",
    "Nghĩa Đàn",
    "Quế Phong",
    "Quỳnh Lưu",
    "Tương Dương",
    "Kỳ Sơn",
    "Tân Kỳ",
    "Anh Sơn",
    "Diễn Châu",
    "Yên Thành",
    "Đô Lương",
    "Thanh Chương",
    "Nam Đàn",
    "Hưng Nguyên",
    "Hòa Bình",
    "Con Cuông",
    "Tương Dương",
  ],
  "Ninh Bình": [
    "Ninh Bình",
    "Tam Điệp",
    "Nho Quan",
    "Gia Viễn",
    "Hoa Lư",
    "Yên Khánh",
    "Kim Sơn",
    "Yên Mô",
  ],
  "Ninh Thuận": [
    "Phan Rang-Tháp Chàm",
    "Bác Ái",
    "Ninh Hải",
    "Ninh Phước",
    "Ninh Sơn",
    "Thuận Bắc",
    "Thuận Nam",
  ],
  "Phú Thọ": [
    "Việt Trì",
    "Phú Thọ",
    "Cẩm Khê",
    "Đoan Hùng",
    "Hạ Hoà",
    "Lâm Thao",
    "Phù Ninh",
    "Tam Nông",
    "Tân Sơn",
    "Thanh Ba",
    "Thanh Sơn",
    "Thanh Thủy",
    "Yên Lập",
  ],
  "Phú Yên": [
    "Tuy Hòa",
    "Sông Cầu",
    "Đồng Xuân",
    "Tuy An",
    "Sơn Hòa",
    "Sông Hinh",
    "Đông Hòa",
    "Tây Hòa",
  ],
  "Quảng Bình": [
    "Đồng Hới",
    "Ba Đồn",
    "Bố Trạch",
    "Lệ Thủy",
    "Minh Hóa",
    "Quảng Ninh",
    "Quảng Trạch",
    "Tuyên Hóa",
  ],
  "Quảng Nam": [
    "Tam Kỳ",
    "Hội An",
    "Duy Xuyên",
    "Đại Lộc",
    "Điện Bàn",
    "Đông Giang",
    "Hiệp Đức",
    "Nam Giang",
    "Nam Trà My",
    "Núi Thành",
    "Phú Ninh",
    "Phước Sơn",
    "Quế Sơn",
    "Tiên Phước",
  ],
  "Quảng Ngãi": [
    "Quảng Ngãi",
    "Bình Sơn",
    "Ba Tơ",
    "Đức Phổ",
    "Minh Long",
    "Mộ Đức",
    "Nghĩa Hành",
    "Sơn Hà",
    "Sơn Tây",
    "Tây Trà",
    "Trà Bồng",
    "Tư Nghĩa",
  ],
  "Quảng Ninh": [
    "Hạ Long",
    "Móng Cái",
    "Cẩm Phả",
    "Uông Bí",
    "Quảng Yên",
    "Đông Triều",
    "U Minh",
  ],
  "Quảng Trị": [
    "Đông Hà",
    "Quảng Trị",
    "Cam Lộ",
    "Cồn Cỏ",
    "Đa Krông",
    "Gio Linh",
    "Hải Lăng",
    "Hướng Hóa",
    "Triệu Phong",
    "Vĩnh Linh",
  ],
  "Sóc Trăng": [
    "Sóc Trăng",
    "Châu Thành",
    "Cù Lao Dung",
    "Kế Sách",
    "Long Phú",
    "Mỹ Tú",
    "Mỹ Xuyên",
    "Ngã Năm",
    "Thạnh Trị",
    "Trần Đề",
    "Vĩnh Châu",
  ],
  "Sơn La": [
    "Sơn La",
    "Bắc Yên",
    "Mai Sơn",
    "Mộc Châu",
    "Mường La",
    "Phù Yên",
    "Quỳnh Nhai",
    "Sông Mã",
    "Thuận Châu",
    "Vân Hồ",
    "Yên Châu",
  ],
  "Tây Ninh": [
    "Tây Ninh",
    "Hòa Thành",
    "Dương Minh Châu",
    "Bến Cầu",
    "Gò Dầu",
    "Tân Biên",
    "Tân Châu",
  ],
  "Thái Bình": [
    "Thái Bình",
    "Đông Hưng",
    "Hưng Hà",
    "Kiến Xương",
    "Quỳnh Phụ",
    "Thái Thụy",
    "Tiền Hải",
    "Vũ Thư",
  ],
  "Thái Nguyên": [
    "Thái Nguyên",
    "Phổ Yên",
    "Đại Từ",
    "Định Hóa",
    "Đồng Hỷ",
    "Phú Bình",
    "Võ Nhai",
  ],
  "Thanh Hóa": [
    "Thanh Hóa",
    "Bỉm Sơn",
    "Sầm Sơn",
    "Bá Thước",
    "Cẩm Thủy",
    "Đông Sơn",
    "Hà Trung",
    "Hậu Lộc",
    "Hoằng Hóa",
    "Lang Chánh",
    "Mường Lát",
    "Nga Sơn",
    "Ngọc Lặc",
    "Như Thanh",
    "Như Xuân",
    "Nông Cống",
    "Quan Hóa",
    "Quan Sơn",
    "Quảng Xương",
    "Thạch Thành",
    "Thiệu Hóa",
    "Thọ Xuân",
    "Thường Xuân",
    "Tĩnh Gia",
    "Triệu Sơn",
    "Vĩnh Lộc",
    "Yên Định",
  ],
  "Thừa Thiên Huế": [
    "Huế",
    "Hương Thủy",
    "Hương Trà",
    "A Lưới",
    "Nam Đông",
    "Phong Điền",
    "Phú Lộc",
    "Phú Vang",
    "Quảng Điền",
  ],
  "Tiền Giang": [
    "Mỹ Tho",
    "Cai Lậy",
    "Cái Bè",
    "Gò Công",
    "Châu Thành",
    "Tân Phước",
    "Cai Lậy",
    "Tân Phú Đông",
  ],
  "Trà Vinh": [
    "Trà Vinh",
    "Càng Long",
    "Cầu Kè",
    "Cầu Ngang",
    "Châu Thành",
    "Duyên Hải",
    "Tiểu Cần",
  ],
  "Tuyên Quang": [
    "Tuyên Quang",
    "Chiêm Hóa",
    "Hàm Yên",
    "Na Hang",
    "Sơn Dương",
    "Yên Sơn",
  ],
  "Vĩnh Long": [
    "Vĩnh Long",
    "Bình Minh",
    "Bình Tân",
    "Long Hồ",
    "Mang Thít",
    "Tam Bình",
    "Trà Ôn",
    "Vũng Liêm",
  ],
  "Vĩnh Phúc": [
    "Vĩnh Yên",
    "Phúc Yên",
    "Lập Thạch",
    "Sông Lô",
    "Tam Đảo",
    "Bình Xuyên",
    "Yên Lạc",
  ],
  "Yên Bái": [
    "Yên Bái",
    "Lục Yên",
    "Mù Cang Chải",
    "Trạm Tấu",
    "Trấn Yên",
    "Văn Chấn",
    "Văn Yên",
  ],
};

export default vietnamAbc;
